name: Build CD

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Change endline (windows)
        if: ${{runner.os == 'Windows'}}
        run: npx chendln -t crlf -i yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Build_Windows
        if: ${{runner.os == 'Windows'}}
        run: yarn build
      - name: Build_Unix
        if: ${{runner.os != 'Windows'}}
        run: USE_HARD_LINKS=false yarn build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-for-${{ runner.os }}
          path: apps/desktop/release/**
          if-no-files-found: error
          retention-days: 1
